### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by spvkgn** [jepler/cropgui#123]
```
$ cropgui ./moon.jpg
Traceback (most recent call last):
  File "/usr/bin/cropgui", line 442, in <module>
    app.run()
  File "/usr/bin/cropgui", line 357, in run
    image_type = thumbnail.format.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

/usr/bin/cropgui:45: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Pleas
e specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: https:
//wiki.gnome.org/PyGObject/InitializerDeprecations
  m = gtk.MessageDialog(w,
/usr/bin/cropgui:45: PyGTKDeprecationWarning: The keyword(s) "message_format" have been deprecated in favor of "text" respective
ly. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  m = gtk.MessageDialog(w,
/usr/bin/cropgui:45: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer
 keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  m = gtk.MessageDialog(w,
```
```
$ apt policy cropgui
cropgui:
  Установлен: 0.8-4-g8138638
  Кандидат:   0.8-4-g8138638
  Таблица версий:
 *** 0.8-4-g8138638 100
        100 /var/lib/dpkg/status
```

**Comment by jepler** [comment]
Thanks for the report & testing!
