### ISSUE TITLE
Thread exception when cropping

### ISSUE THREAD

**Issue by logological** [jepler/cropgui#27]
Whenever I press the "Crop" button in the GTK+ version of cropgui, the following is output to the console:
```
nice jpegtran -copy all -crop 3832x2984+720+0 -outfile /tmp/foo-crop.jpg foo.jpg
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/cropgui_common.py", line 87, in runner
    subprocess.call(["jpegexiforient", "-1", target])
  File "/usr/lib64/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
The cropped file is nonetheless successfully written.

**Comment by jepler** [comment]
jpegexiforient is used to clear the orientation tag in the output image.  If this is not done, some programs will rotate the image a second time (issue #4).

On Debian systems, jpegtran and jpegexiforient both come from the same package, so this problem is not possible to notice there.

**Comment by logological** [comment]
I'm not sure I understand your comment, Jeff.  Are you saying the error message is unavoidable?

**Comment by jepler** [comment]
You need to resolve the problem on your own system by installing the "jpegexiforient" program.  It may come from an operating system package, it's not part of cropgui.
