### ISSUE TITLE
install.sh mixes python3 script with python2 modules

### ISSUE THREAD

**Issue by jose1711** [jepler/cropgui#67]
after `./install.sh -f gtk -t $pkgdir -p /usr -P /usr/bin/python` and packaging `cropgui` for Arch Linux I get a `python3` script:
```
$ head -1 /usr/bin/cropgui
#!/usr/bin/python3
```
with `python2` modules:
```
$ pacman -Ql cropgui | grep python2.7
cropgui /usr/lib/python2.7/
cropgui /usr/lib/python2.7/site-packages/
cropgui /usr/lib/python2.7/site-packages/cropgui.glade
cropgui /usr/lib/python2.7/site-packages/cropgui_common.py
cropgui /usr/lib/python2.7/site-packages/filechooser.py
cropgui /usr/lib/python2.7/site-packages/stock-rotate-270-16.png
cropgui /usr/lib/python2.7/site-packages/stock-rotate-90-16.png
```
This of course does not work:
```
$ cropgui
/usr/bin/cropgui:294: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif image_type is "jpeg":
Traceback (most recent call last):
  File "/usr/bin/cropgui", line 18, in <module>
    from cropgui_common import *
ModuleNotFoundError: No module named 'cropgui_common'

```

**Comment by spvkgn** [comment]
This works
```
--- a/install.sh
+++ b/install.sh
@@ -12,7 +12,7 @@
 }
 
 site_packages () {
-    $PYTHON -c 'import distutils.sysconfig; print distutils.sysconfig.get_python_lib()'
+    $PYTHON -c 'import distutils.sysconfig; print(distutils.sysconfig.get_python_lib())'
 }
 
 usage () {
```

**Comment by protist** [comment]
That merged pull request still doesn't fix it for me. I can still see the mix of python3 and python2, after running commands as per the original post.

After updating, the error message is slightly different though. The first two lines are gone, and only the second part remains.
```
$ cropgui
Traceback (most recent call last):
  File "/usr/bin/cropgui", line 18, in <module>
    from cropgui_common import *
ModuleNotFoundError: No module named 'cropgui_common'
```

**Comment by spvkgn** [comment]
@protist Try to replace `PYTHON=python2` with `python3` in `install.sh`

**Comment by protist** [comment]
Perfect! Thanks @spvkgn, that fixes it.
