### ISSUE TITLE
get_primary_monitor() doesn't work with Wayland and is deprecated

### ISSUE THREAD

**Issue by wanted0** [jepler/cropgui#93]
Trying to run the latest cropgui (cropgtk.py) on Ubuntu 21.04 fails with:
```
$ ./cropgtk.py 
Traceback (most recent call last):
  File "/tmp/./cropgtk.py", line 223, in <module>
    wa = display.get_primary_monitor().get_workarea()
AttributeError: 'NoneType' object has no attribute 'get_workarea'
```
I figured out that get_primary_monitor() returns None in my configuration because Ubuntu 21.04 introduced Wayland as a default.

Wayland doesn't provide the necessary API for this function and it seems GTK will also deprecate it in 4.0:
https://gitlab.gnome.org/GNOME/gtk/-/issues/1028

Applying the following patch fixes the issue for me:
```
--- cropgtk_orig.py	2021-10-04 20:33:02.398149075 +0200
+++ cropgtk.py	2021-10-04 20:34:04.880647475 +0200
@@ -220,7 +220,7 @@
         return self.result
 
 display = gdk.Display().get_default()
-wa = display.get_primary_monitor().get_workarea()
+wa = display.get_monitor(0).get_workarea()
 max_h = wa.height - 192
 max_w = wa.width - 64
```

**Comment by jepler** [comment]
Thanks! Would be happy to accept a PR making this change.

https://valadoc.org/gdk-3.0/Gdk.Display.get_monitor.html indicates that the API you propose using is available since 3.22, which means this is compatible with debian oldstable and newer, so it should be fine.

**Comment by jepler** [comment]
Another possible alternative is querying the pointer location and using the monitor that contains it: https://valadoc.org/gdk-3.0/Gdk.Display.get_monitor_at_point.html -- implementing "open on current monitor" instead of "open on primary monitor"

**Comment by JoKalliauer** [comment]
I get the same reply on Fedora 35 (with Wayland), with `python3.10 ./cropgtk.py `

```bash
Traceback (most recent call last):
  File "/home/jkalliau/Documents/GitHub/cropgui/./cropgtk.py", line 223, in <module>
    wa = display.get_primary_monitor().get_workarea()
AttributeError: 'NoneType' object has no attribute 'get_workarea'

/home/jkalliau/Documents/GitHub/cropgui/./cropgtk.py:45: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  m = gtk.MessageDialog(w,
/home/jkalliau/Documents/GitHub/cropgui/./cropgtk.py:45: PyGTKDeprecationWarning: The keyword(s) "message_format" have been deprecated in favor of "text" respectively. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  m = gtk.MessageDialog(w,
/home/jkalliau/Documents/GitHub/cropgui/./cropgtk.py:45: PyGTKDeprecationWarning: The "flags" argument for dialog construction is deprecated. Please use initializer keywords: modal=True and/or destroy_with_parent=True. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  m = gtk.MessageDialog(w,
```
![Screenshot from 2021-12-23 14-18-02](https://user-images.githubusercontent.com/15687581/147246128-d7b26874-ef82-4856-a861-58ececab3042.png)

```
 Static hostname: lws84.imws.tuwien.ac.at
       Icon name: computer-laptop
         Chassis: laptop
      Machine ID: 96434f58f7644401a3f9d69da903899d
         Boot ID: 41cc9898ec1748fba607820c8849e383
Operating System: Fedora Linux 35 (Workstation Edition)
     CPE OS Name: cpe:/o:fedoraproject:fedora:35
          Kernel: Linux 5.15.10-200.fc35.x86_64
    Architecture: x86-64
 Hardware Vendor: Lenovo
  Hardware Model: ThinkPad P15 Gen 1
```

`python --version` returns `Python 3.10.1`

**Comment by eleius** [comment]
Same error on Arch Linux (gnome-shell 41.3, python 3.10.2)
