### ISSUE TITLE
Incompatible with Python 3.10

### ISSUE THREAD

**Issue by jose1711** [jepler/cropgui#94]
```
image_rotation 1
apply_rotation 1
image_rotation 1
apply_rotation 1
/usr/bin/cropgui:235: DeprecationWarning: Gtk.Widget.get_pointer is deprecated
  self.drag.idle_motion(*i.get_pointer())
Traceback (most recent call last):
  File "/usr/bin/cropgui", line 329, in <module>
    app.run()
  File "/usr/bin/cropgui", line 264, in run
    drag.image = thumbnail
  File "/usr/lib/python3.10/site-packages/cropgui_common.py", line 198, in set_image
    self.image_or_rotation_changed()
  File "/usr/lib/python3.10/site-packages/cropgui_common.py", line 214, in image_or_rotation_changed
    ImageFilter.SMOOTH_MORE).point([x/2 for x in range(256)] * mult)
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 1680, in point
    return self._new(self.im.point(lut, mode))
TypeError: 'float' object cannot be interpreted as an integer

```

**Comment by protist** [comment]
Thanks for the quick fix @jepler. I can confirm cropgui is working perfectly again.

**Comment by jepler** [comment]
Great, thanks for the report
